name: Prompt Inactive Issues

on:
  schedule:
    - cron: '0 5 * * 2'  # Runs every xxxday at 5:00 AM

jobs:
  check-inactive-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check inactive issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const someTimeAgo = new Date();
            someTimeAgo.setDate(oneWeekAgo.getDate() - 0.5);

            const { data: issues } = await github.rest.issues.listForRepo({
              ...context.repo,
              state: 'open',
              assignee: '*'
            });

            for (const issue of issues) {
              if (new Date(issue.updated_at) < oneWeekAgo) {
                const assignee = issue.assignee.login;
                const message = `Hi @${assignee}, we noticed that there's been no activity on "${issue.title}" in the last week or so. Are you still working on this? Please let us know if you want us to re-assign this task. Thank you for your contributions as always.`;

                await github.rest.issues.createComment({
                  ...context.repo,
                  issue_number: issue.number,
                  body: message
                });
              }
            }

